FMS/FMS/FMS/Models/ORDERS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int C_Order_id { get; set; }
        public string C_Food_id { get; set; }
        public string C_Staff_id { get; set; }
        public string C_Shift_id { get; set; }
        public Nullable<System.DateTime> C_Order_date { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual SPLIT_TIME SPLIT_TIME { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}

FMS/FMS/FMS/Models/STAFF.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.LOGIN = new HashSet<LOGIN>();
            this.ORDERS = new HashSet<ORDERS>();
            this.SPLIT_SHIFTS = new HashSet<SPLIT_SHIFTS>();
        }
    
        public string C_Staff_id { get; set; }
        public string C_Staff_name { get; set; }
        public Nullable<System.DateTime> C_Birthday { get; set; }
        public Nullable<bool> C_Gender { get; set; }
        public string C_Identity_card { get; set; }
        public string C_Position { get; set; }
        public string C_phone_number { get; set; }
        public string C_Ward { get; set; }
        public string C_District { get; set; }
        public string C_City { get; set; }
        public string C_Department_id { get; set; }
        public string C_Face_id { get; set; }
        public string C_Image { get; set; }
        public string C_Ethnic { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual FACE FACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIN> LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPLIT_SHIFTS> SPLIT_SHIFTS { get; set; }
    }
}

FMS/FMS/FMS/Areas/Admin/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.Models;
using System.Web.Security;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

namespace FMS.Areas.Admin.Controllers
{
    public class StaffController : Controller
    {
        // GET: Admin/Staff
        db_FMSEntities db = new db_FMSEntities();
        public ActionResult Order()
        {
            return View(db.MENU.ToList());
        }

        public ActionResult Orderfood(string id)
        {
            var ord = db.MENU.Where(s => s.C_Food_id == id).FirstOrDefault();
            if (ord != null)
            {
                FoodValidate fv = new FoodValidate();
                fv.FoodID = ord.C_Food_id;
                fv.FoodName = ord.C_Food_name;
                fv.FoodDescrip = ord.C_Description;
                return View(fv);
            }
            return Redirect("~/Admin/Staff/Order");
        }

        [HttpPost]
        public ActionResult Orderfood(FoodValidate fv)
        {
            var id = Session["C_Staff_id"] as String;
            var checkst = db.ORDERS.Any(s => s.C_Order_id == fv.Orderid);
            if (checkst)
            {
                ViewBag.err = "Order ID already exist"; 
                return View(fv);
            }
            else
            {
                ORDERS Addor = new ORDERS();
                Addor.C_Order_id = fv.Orderid;
                Addor.C_Food_id = fv.FoodID;
                Addor.C_Staff_id = id;
                Addor.C_Shift_id = fv.Shiftid;
                Addor.C_Order_date = DateTime.Today;

                db.ORDERS.Add(Addor);
                db.SaveChanges();
                return Redirect("~/Admin/Staff/Order");
            }
            
        }

        public ActionResult PersonalPro(){
            var id = Session["C_Staff_id"] as String;
            var empl = db.STAFF.Where(n => n.C_Staff_id == id).FirstOrDefault();
            if (empl != null)
            {
                UserValidate us = new UserValidate();
                us.StaffName = empl.C_Staff_name;
                us.Birthday = (DateTime)empl.C_Birthday;
                us.Gender = (bool)empl.C_Gender;
                us.Image = empl.C_Image;
                us.PhoneNumber = empl.C_phone_number;
                us.Position = empl.C_Position;
                us.IdentityCard = empl.C_Identity_card;
                us.Ward = empl.C_Ward;
                us.District = empl.C_District;
                us.Ethnic = empl.C_Ethnic;
                us.City = empl.C_City;
                us.DepartmentID = empl.C_Department_id;
                return View(us);
            }
            else
            {
                return Redirect("~/Admin/Staff/PersonalPro");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PersonalPro(UserValidate us, HttpPostedFileBase Image){
            var id = Session["C_Staff_id"] as String;
            var checkst = db.STAFF.Where(n => n.C_Staff_id == id).FirstOrDefault();
            if (checkst != null)
            {
                checkst.C_Staff_name = us.StaffName;
                checkst.C_Birthday = us.Birthday;
                checkst.C_Gender = us.Gender;
                checkst.C_phone_number = us.PhoneNumber;
                checkst.C_Identity_card = us.IdentityCard;
                checkst.C_Position = us.Position;
                checkst.C_Ward = us.Ward;
                checkst.C_District = us.District;
                checkst.C_City = us.City;
                checkst.C_Ethnic = us.Ethnic;
                checkst.C_Department_id = us.DepartmentID;
                if (Image != null && Image.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(Image.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Content/image"), _FileName);
                    Image.SaveAs(_path);
                    /*Image.SaveAs(HttpContext.Server.MapPath("~/Content/images/") + Image.FileName);*/
                    checkst.C_Image = Image.FileName;
                    us.Image = Image.FileName;
                }
                else
                {
                    us.Image = checkst.C_Image;
                }

                db.SaveChanges();
                return Redirect("~/Admin/Staff/PersonalPro");
            }
            else
            {
                ViewBag.err = "Staff ID does not exist";
                return View(us);
            }
        }

        public ActionResult DeleteOrd(int id)
        {
            var order = db.ORDERS.Where(n => n.C_Order_id == id).FirstOrDefault();
            if (order != null)
            {
                db.ORDERS.Remove(order);
                db.SaveChanges();
                return Redirect("~/StaffS/StaffS/Order");
            }
            return Redirect("~/StaffS/StaffS/Order");
        }
    }
}

FMS/FMS/FMS/Areas/StaffS/Controllers/StaffSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.Models;
using System.Web.Security;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

namespace FMS.Areas.StaffS.Controllers
{
    public class StaffSController : Controller
    {
        // GET: StaffS/StaffS
        // GET: Admin/Staff
        db_FMSEntities db = new db_FMSEntities();
        public ActionResult Order()
        {
            return View(db.MENU.ToList());
        }

        public ActionResult Orderfood(string id)
        {
            var ord = db.MENU.Where(s => s.C_Food_id == id).FirstOrDefault();
            if (ord != null)
            {
                FoodValidate fv = new FoodValidate();
                fv.FoodID = ord.C_Food_id;
                fv.FoodName = ord.C_Food_name;
                fv.FoodDescrip = ord.C_Description;
                return View(fv);
            }
            return Redirect("~/StaffS/StaffS/Order");
        }

        [HttpPost]
        public ActionResult Orderfood(FoodValidate fv)
        {
            var id = Session["C_Staff_id"] as String;
            var checkst = db.ORDERS.Any(s => s.C_Order_id == fv.Orderid);
            if (checkst)
            {
                ViewBag.err = "Order ID already exist";
                //ModelState.AddModelError("MaNhanVien", "Mã tài khoản đã tồn tại");
                return View(fv);
            }
            else
            {
                ORDERS Addor = new ORDERS();
                Addor.C_Order_id = fv.Orderid;
                Addor.C_Food_id = fv.FoodID;
                Addor.C_Staff_id = id;
                Addor.C_Shift_id = fv.Shiftid;
                Addor.C_Order_date = DateTime.Today;

                db.ORDERS.Add(Addor);
                db.SaveChanges();
                return Redirect("~/StaffS/StaffS/Order");
            }

        }

        public ActionResult PersonalPro()
        {
            var id = Session["C_Staff_id"] as String;
            var empl = db.STAFF.Where(n => n.C_Staff_id == id).FirstOrDefault();
            if (empl != null)
            {
                UserValidate us = new UserValidate();
                us.StaffName = empl.C_Staff_name;
                us.Birthday = (DateTime)empl.C_Birthday;
                us.Gender = (bool)empl.C_Gender;
                us.Image = empl.C_Image;
                us.PhoneNumber = empl.C_phone_number;
                us.Position = empl.C_Position;
                us.IdentityCard = empl.C_Identity_card;
                us.Ward = empl.C_Ward;
                us.District = empl.C_District;
                us.Ethnic = empl.C_Ethnic;
                us.City = empl.C_City;
                us.DepartmentID = empl.C_Department_id;
                return View(us);
            }
            else
            {
                return Redirect("~/StaffS/StaffS/PersonalPro");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PersonalPro(UserValidate us, HttpPostedFileBase Image)
        {
            var id = Session["C_Staff_id"] as String;
            var checkst = db.STAFF.Where(n => n.C_Staff_id == id).FirstOrDefault();
            if (checkst != null)
            {
                checkst.C_Staff_name = us.StaffName;
                checkst.C_Birthday = us.Birthday;
                checkst.C_Gender = us.Gender;
                checkst.C_phone_number = us.PhoneNumber;
                checkst.C_Identity_card = us.IdentityCard;
                checkst.C_Position = us.Position;
                checkst.C_Ward = us.Ward;
                checkst.C_District = us.District;
                checkst.C_City = us.City;
                checkst.C_Ethnic = us.Ethnic;
                checkst.C_Department_id = us.DepartmentID;
                if (Image != null && Image.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(Image.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Content/image"), _FileName);
                    Image.SaveAs(_path);
                    /*Image.SaveAs(HttpContext.Server.MapPath("~/Content/images/") + Image.FileName);*/
                    checkst.C_Image = Image.FileName;
                    us.Image = Image.FileName;
                }
                else
                {
                    us.Image = checkst.C_Image;
                }

                db.SaveChanges();
                return Redirect("~/StaffS/StaffS/PersonalPro");
            }
            else
            {
                ViewBag.err = "Staff ID does not exist";
                return View(us);
            }
        }

        public ActionResult DeleteOrd(int id)
        {
            var order = db.ORDERS.Where(n => n.C_Order_id == id).FirstOrDefault();
            if (order != null)
            {
                db.ORDERS.Remove(order);
                db.SaveChanges();
                return Redirect("~/StaffS/StaffS/Order");
            }
            return Redirect("~/StaffS/StaffS/Order");
        }
    }
}

FMS/FMS/FMS/Areas/Admin/Views/Staff/DeleteOrd.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeleteOrd</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

FMS/FMS/FMS/Areas/Admin/Views/Staff/Order.cshtml
@{
    Layout = "~/Views/Shared/_logoutlayout.cshtml";
    ViewBag.Title = "Order";
}
@using FMS.Models
@model List<MENU>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order</title>
    <link rel="stylesheet" href="~/Content/admincss/menuadim/homepageadmin.css">
    <link rel="stylesheet" href="~/Content/admin/3.chef/1.managemenu/1.managemenu.css">
    <link rel="stylesheet" href="~/Content/admin/3.chef/2.managesupplier/2.managespplier.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

</head>
<body>
    <!-- html cho phần menu -->
    <div class="navigation open">
        <div class="menuToggle">Admin</div>
        <div class="main-menu">
            <div class="dropdown">
                <input type="text" class="text02" readonly placeholder="Dropdown Menu">
                <div class="options">
                    <div class="change-option-admin" onmouseover="show('Admin')">Admin</div>
                    <div class="change-option-manage" onmouseover="show('Management')">Management</div>
                    <div class="change-option-cheif" onmouseover="show('Cheif')">Cheif</div>
                    <div class="change-option-staff" onmouseover="show('Staff')">Staff</div>
                </div>
            </div>
            <div class="menu-option">
                <ul class="admin">
                    <li class="list " style="--clr:#f44336;">
                        <a href="@Url.Action("ManageAcc","Admin")">
                            <span class="icon"><ion-icon name="desktop-outline"></ion-icon></span>
                            <span class="text">Manage Account</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("ManageEmploy","Admin")">
                            <span class="icon"><ion-icon name="people-outline"></ion-icon></span>
                            <span class="text">Manage Employee</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#4f088a;">
                        <a href="@Url.Action("ManageDepart","Admin")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Manage Department</span>
                        </a>
                    </li>
                    <li class="list " style="--clr:#0fc70f;">
                        <a href="@Url.Action("FaceID","Admin")">
                            <span class="icon"><ion-icon name="grid-outline"></ion-icon></span>
                            <span class="text">Manage Face Pattern</span>
                        </a>
                    </li>
                </ul>
                <ul class="manage">
                    <li class="list" style="--clr:#f44336;">
                        <a href="@Url.Action("ManagePro","Manager")">
                            <span class="icon"><ion-icon name="newspaper-outline"></ion-icon></span>
                            <span class="text">Manage Profile</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("ManageWorkshift","Manager")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Manage WorkShift</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#4f088a;">
                        <a href="@Url.Action("TimeKeeping","Manager")">
                            <span class="icon"><ion-icon name="today-outline"></ion-icon></span>
                            <span class="text">TimeKeeping</span>
                        </a>
                    </li>
                    <li class="list " style="--clr:#2196f3;">
                        <a href="@Url.Action("ReportStatis","Manager")">
                            <span class="icon"><ion-icon name="document-text-outline"></ion-icon></span>
                            <span class="text">Report Statistics</span>
                        </a>
                    </li>
                </ul>
                <ul class="cheif">
                    <li class="list" style="--clr:#f44336;">
                        <a href="@Url.Action("ManageMenu","Chef")">
                            <span class="icon"><ion-icon name="receipt-outline"></ion-icon></span>
                            <span class="text">Manage Menu</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("ManageSupp","Chef")">
                            <span class="icon"><ion-icon name="receipt-outline"></ion-icon></span>
                            <span class="text">Manage Supplier</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#4f088a;">
                        <a href="@Url.Action("ManageMaterial","Chef")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Manage Material</span>
                        </a>
                    </li>
                    <li class="list " style="--clr:#0fc70f;">
                        <a href="@Url.Action("ViewRegis","Chef")">
                            <span class="icon"><ion-icon name="clipboard-outline"></ion-icon></span>
                            <span class="text">View Registration</span>
                        </a>
                    </li>
                </ul>
                <ul class="staff showstaff">
                    <li class="list active" style="--clr:#f44336;">
                        <a href="@Url.Action("Order", "Staff")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Order</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("PersonalPro", "Staff")">
                            <span class="icon"><ion-icon name="person-outline"></ion-icon></span>
                            <span class="text">Personal profile</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- end menu -->

    <!-- html cho phần nội dung -->
    <div class="home-main open3">
        <div class="header-content">
            <p>Order</p>
        </div>
        <hr>
        <div class="table-food">
            <div class="khungtable">
                <div class="content">
                    <p>Menu</p>
                </div>
                <div class="table-monan">
                    <table border="1">
                        <thead>
                            <tr class="success">
                                <td>Image</td>
                                <td>Food ID</td>
                                <td>Food Name</td>
                                <td>Description</td>
                                <td>Status</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th><img src="~/Content/image/@item.C_Imagefood" alt="" width="10%"></th>
                                    <th>@item.C_Food_id</th>
                                    <th>@item.C_Food_name</th>
                                    <th>@item.C_Description</th>
                                    <th>
                                        <button type="submit" class="btn-delete" style="border: none;">
                                            <a href="@Url.Action("Orderfood","Staff",new { @id = @item.C_Food_id })"><div class=" btn btn-success">Order</div></a>
                                        </button>
                                    </th>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="table-food">
            <div class="khungtable">
                <div class="content">
                    <p>Order</p>
                </div>
                <div class="table-monan">
                    <table border="1">
                        <tr>
                            <td class="td-img"></td>
                            <td class="width-36">Food Name</td>
                            <td class="td-mota">Description</td>
                            <td class="td-mota">Status</td>
                        </tr>

                        <tr>
                            @{
                                db_FMSEntities db = new db_FMSEntities();
                                var ord = db.ORDERS.ToList();

                            }
                            @foreach (var item in ord)
                            {
                                <tr>
                                    @{ 
                                        var menu = db.MENU.ToList();
                                        var id = Session["C_Staff_id"] as String;
                                    }

                                    @{ 
                                        foreach (var mitem in menu)
                                        {
                                            if(item.C_Food_id == mitem.C_Food_id && item.C_Staff_id == id)
                                            {
                                                <th><img src="~/Content/image/" alt="" width="10%"></th>
                                                <th>@mitem.C_Food_name</th>
                                                <th>@mitem.C_Description</th>
                                                <th>
                                                    <button type="submit" class="btn-delete" style="border: none;">
                                                        <a href="@Url.Action("DeleteOrd","Staff",new { @id = @item.C_Order_id })"><div class=" btn btn-success">Delete</div></a>
                                                    </button>
                                                </th>
                                            }
                                        }
                                    }
                                    

                                    
                                </tr>
                            }
                        </tr>

                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- end nội dung -->

    <script>
        // script cho phần profile
        let menuToggleprofile = document.querySelector('.menuToggle-profile');
        let navigationprofile = document.querySelector('.navigation-profile')
        menuToggleprofile.onclick = function(){
            navigationprofile.classList.toggle('active')
        }

        // script cho phần option role
        function show(a){
           document.querySelector('.navigation.open .text02').value = a;
        }

        let dropdown = document.querySelector('.dropdown');
        dropdown.onclick = function(){
            dropdown.classList.toggle('dropdownactive');
        }

        //script cho phần đổi menu
        const changeadmin = document.querySelector('.change-option-admin');
        const changemanage = document.querySelector('.change-option-manage');
        const changecheif = document.querySelector('.change-option-cheif');
        const changestaff = document.querySelector('.change-option-staff');
        const admin = document.querySelector('.admin');
        const manage = document.querySelector('.manage');
        const cheif = document.querySelector('.cheif');
        const staff = document.querySelector('.staff');

        changeadmin.onclick = function(){
            admin.classList.add('showadmin');
            manage.classList.remove('showmanage');
            cheif.classList.remove('showcheif');
            staff.classList.remove('showstaff');
        }
        changemanage.onclick = function(){
            admin.classList.remove('showadmin');
            manage.classList.add('showmanage');
            cheif.classList.remove('showcheif');
            staff.classList.remove('showstaff');
        }
        changecheif.onclick = function(){
            admin.classList.remove('showadmin');
            manage.classList.remove('showmanage');
            cheif.classList.add('showcheif');
            staff.classList.remove('showstaff');
        }
        changestaff.onclick = function(){
            admin.classList.remove('showadmin');
            manage.classList.remove('showmanage');
            cheif.classList.remove('showcheif');
            staff.classList.add('showstaff');
        }
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>
</html>