FMS/FMS/FMS/Areas/Admin/Controllers/ChefController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.Models;
using System.Web.Security;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
namespace FMS.Areas.Admin.Controllers
{
    public class ChefController : Controller
    {
        // GET: Admin/Chef
        db_FMSEntities db = new db_FMSEntities();
        //Manage menu
        public ActionResult ManageMenu()
        {
            return View(db.MENU.ToList());
        }
        public ActionResult Addfood()
        {
            return View(new FoodValidate());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Addfood(FoodValidate fv)
        {
            var checkfd = db.MENU.Any(x => x.C_Food_id == fv.FoodID);
            if (checkfd == false)
            {
                MENU adfd = new MENU();
                adfd.C_Food_id = fv.FoodID;
                adfd.C_Food_name = fv.FoodName;
                adfd.C_Description = fv.FoodDescrip;
                db.MENU.Add(adfd);
                db.SaveChanges();
                return Redirect("~/admin/Chef/ManageMenu");
            }
            else
            {
                ViewBag.err = "Food already exist";
                return View(fv);
            }
        }
        public ActionResult Deletefood(String id)
        {
            var fd = db.MENU.Where(n => n.C_Food_id == id).FirstOrDefault();
            if (fd != null)
            {
                db.MENU.Remove(fd);
                db.SaveChanges();
                return Redirect("~/admin/Chef/ManageMenu");
            }
            return Redirect("~/admin/Chef/ManageMenu");
        }
        //Manage supplier
        public ActionResult ManageSupp()
        {
            return View(db.SUPPLIER.ToList());
        }
        public ActionResult Addsupplier()
        {
            return View(new SupplierValidate());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Addsupplier(SupplierValidate sp)
        {
            var checksp = db.SUPPLIER.Any(x => x.C_Supplier_id == sp.SupplierID);
            if (checksp == false)
            {
                SUPPLIER spadd = new SUPPLIER();
                spadd.C_Supplier_id = sp.SupplierID;
                spadd.C_Supplier_name = sp.SupplierName;
                spadd.C_Supplier_phone = sp.SupplierPhone;
                spadd.C_Supplier_address = sp.SupplierAddress;
                db.SUPPLIER.Add(spadd);
                db.SaveChanges();
                return Redirect("~/admin/Chef/ManageSupp");
            }
            else
            {
                ViewBag.err = "Supplier already exist";
                return View(sp);
            }
        }
        public ActionResult Updatefood(String id)
        {
            var checksp = db.MENU.Where(n => n.C_Food_id == id).FirstOrDefault();
            FoodValidate sp = new FoodValidate();
            sp.FoodID = checksp.C_Food_id;
            sp.FoodName = checksp.C_Food_name;
            sp.FoodDescrip = checksp.C_Description;
            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Updatefood(FoodValidate sp)
        {
            var checksp = db.MENU.Where(x => x.C_Food_id == sp.FoodID).FirstOrDefault();
            if (checksp != null)
            {
                checksp.C_Food_name = sp.FoodName;
                checksp.C_Description = sp.FoodDescrip;
                db.SaveChanges();
                return Redirect("~/admin/Chef/ManageMenu");
            }
            else
            {
                ViewBag.err = "Food do not exist";
                return View(sp);
            }
        }
        public ActionResult Updatesupplier(String id)
        {
            var checksp = db.SUPPLIER.Where(n => n.C_Supplier_id == id).FirstOrDefault();
            SupplierValidate sp = new SupplierValidate();
            sp.SupplierID = checksp.C_Supplier_id;
            sp.SupplierName = checksp.C_Supplier_name;
            sp.SupplierPhone = checksp.C_Supplier_phone;
            sp.SupplierAddress = checksp.C_Supplier_address;
            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Updatesupplier(SupplierValidate sp)
        {
            var checksp = db.SUPPLIER.Where(x => x.C_Supplier_id == sp.SupplierID).FirstOrDefault();
            if (checksp != null)
            {
                checksp.C_Supplier_id = sp.SupplierID;
                checksp.C_Supplier_name = sp.SupplierName;
                checksp.C_Supplier_phone = sp.SupplierPhone;
                checksp.C_Supplier_address = sp.SupplierAddress;
                db.SaveChanges();
                return Redirect("~/admin/Chef/ManageSupp");
            }
            else
            {
                ViewBag.err = "Supplier do not exist";
                return View(sp);
            }
        }
        public ActionResult DeleteSupp(String id)
        {
            var fd = db.SUPPLIER.Where(n => n.C_Supplier_id == id).FirstOrDefault();
            if (fd != null)
            {
                db.SUPPLIER.Remove(fd);
                db.SaveChanges();
                return Redirect("~/admin/Chef/ManageSupp");
            }
            return Redirect("~/admin/Chef/ManageSupp");
        }
        //Manage Material
        public ActionResult ManageMaterial()
        {
            return View(db.INGREDIENT.ToList());
        }
        public ActionResult Addmaterial()
        {
            return View(new MaterialValidate());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Addmaterial(MaterialValidate mr)
        {
            var checkma = db.INGREDIENT.Any(x => x.C_Material_id == mr.MaterialID);
            if (checkma == false)
            {
                INGREDIENT mrAdd = new INGREDIENT();
                mrAdd.C_Material_id = mr.MaterialID;
                mrAdd.C_Material_name = mr.MaterialName;
                mrAdd.C_Quantity_I = mr.MaterialQT;
                mrAdd.C_Unit = mr.MaterialUnit;
                db.INGREDIENT.Add(mrAdd);
                db.SaveChanges();
                return Redirect("~/Admin/Chef/ManageMaterial");
            }
            else
            {
                ViewBag.err = "Material already exist";
                return View(mr);
            }
        }
        public ActionResult Updatematerial(String id)
        {
            var checkmt = db.INGREDIENT.Where(n => n.C_Material_id == id).FirstOrDefault();
            MaterialValidate mt = new MaterialValidate();
            mt.MaterialID = checkmt.C_Material_id;
            mt.MaterialName = checkmt.C_Material_name;
            mt.MaterialQT = checkmt.C_Quantity_I;
            mt.MaterialUnit = checkmt.C_Unit;
            return View(mt);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Updatematerial(MaterialValidate mr)
        {
            var checkmr = db.INGREDIENT.Where(n => n.C_Material_id == mr.MaterialID).FirstOrDefault();
            if (checkmr != null)
            {
                checkmr.C_Material_id = mr.MaterialID;
                checkmr.C_Material_name = mr.MaterialName;
                checkmr.C_Quantity_I = mr.MaterialQT;
                checkmr.C_Unit = mr.MaterialUnit;
                db.SaveChanges();
                return Redirect("~/Admin/Chef/ManageMaterial");
            }
            else
            {
                ViewBag.err = "Material ID does not exist";
                return View(mr);
            }
        }
        public ActionResult Deletematerial(String id)
        {
            var mr = db.INGREDIENT.Where(n => n.C_Material_id == id).FirstOrDefault();
            if (mr != null)
            {
                db.INGREDIENT.Remove(mr);
                db.SaveChanges();
                return Redirect("~/Admin/Chef/ManageMaterial");
            }
            return Redirect("~/Admin/Chef/ManageMaterial");
        }
        //View Registration
        public ActionResult ViewRegis()
        {
            return View();
        }
    }
}

FMS/FMS/FMS/Areas/Chef/Controllers/ChefSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.Models;
using System.Web.Security;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

namespace FMS.Areas.Chef.Controllers
{
    public class ChefSController : Controller
    {
        // GET: Admin/Chef
        db_FMSEntities db = new db_FMSEntities();
        //Manage menu
        public ActionResult ManageMenu()
        {
            return View(db.MENU.ToList());
        }
        public ActionResult Addfood()
        {
            return View(new FoodValidate());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Addfood(FoodValidate fv)
        {
            var checkfd = db.MENU.Any(x => x.C_Food_id == fv.FoodID);
            if (checkfd == false)
            {
                MENU adfd = new MENU();
                adfd.C_Food_id = fv.FoodID;
                adfd.C_Food_name = fv.FoodName;
                adfd.C_Description = fv.FoodDescrip;
                db.MENU.Add(adfd);
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageMenu");
            }
            else
            {
                ViewBag.err = "Food already exist";
                return View(fv);
            }
        }
        public ActionResult Deletefood(String id)
        {
            var fd = db.MENU.Where(n => n.C_Food_id == id).FirstOrDefault();
            if (fd != null)
            {
                db.MENU.Remove(fd);
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageMenu");
            }
            return Redirect("~/Chef/ChefS/ManageMenu");
        }
        //Manage supplier
        public ActionResult ManageSupp()
        {
            return View(db.SUPPLIER.ToList());
        }
        public ActionResult Addsupplier()
        {
            return View(new SupplierValidate());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Addsupplier(SupplierValidate sp)
        {
            var checksp = db.SUPPLIER.Any(x => x.C_Supplier_id == sp.SupplierID);
            if (checksp == false)
            {
                SUPPLIER spadd = new SUPPLIER();
                spadd.C_Supplier_id = sp.SupplierID;
                spadd.C_Supplier_name = sp.SupplierName;
                spadd.C_Supplier_phone = sp.SupplierPhone;
                spadd.C_Supplier_address = sp.SupplierAddress;
                db.SUPPLIER.Add(spadd);
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageSupp");
            }
            else
            {
                ViewBag.err = "Supplier already exist";
                return View(sp);
            }
        }
        public ActionResult Updatefood(String id)
        {
            var checksp = db.MENU.Where(n => n.C_Food_id == id).FirstOrDefault();
            FoodValidate sp = new FoodValidate();
            sp.FoodID = checksp.C_Food_id;
            sp.FoodName = checksp.C_Food_name;
            sp.FoodDescrip = checksp.C_Description;
            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Updatefood(FoodValidate sp)
        {
            var checksp = db.MENU.Where(x => x.C_Food_id == sp.FoodID).FirstOrDefault();
            if (checksp != null)
            {
                checksp.C_Food_name = sp.FoodName;
                checksp.C_Description = sp.FoodDescrip;
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageMenu");
            }
            else
            {
                ViewBag.err = "Food do not exist";
                return View(sp);
            }
        }
        public ActionResult Updatesupplier(String id)
        {
            var checksp = db.SUPPLIER.Where(n => n.C_Supplier_id == id).FirstOrDefault();
            SupplierValidate sp = new SupplierValidate();
            sp.SupplierID = checksp.C_Supplier_id;
            sp.SupplierName = checksp.C_Supplier_name;
            sp.SupplierPhone = checksp.C_Supplier_phone;
            sp.SupplierAddress = checksp.C_Supplier_address;
            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Updatesupplier(SupplierValidate sp)
        {
            var checksp = db.SUPPLIER.Where(x => x.C_Supplier_id == sp.SupplierID).FirstOrDefault();
            if (checksp != null)
            {
                checksp.C_Supplier_id = sp.SupplierID;
                checksp.C_Supplier_name = sp.SupplierName;
                checksp.C_Supplier_phone = sp.SupplierPhone;
                checksp.C_Supplier_address = sp.SupplierAddress;
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageSupp");
            }
            else
            {
                ViewBag.err = "Supplier do not exist";
                return View(sp);
            }
        }
        public ActionResult DeleteSupp(String id)
        {
            var fd = db.SUPPLIER.Where(n => n.C_Supplier_id == id).FirstOrDefault();
            if (fd != null)
            {
                db.SUPPLIER.Remove(fd);
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageSupp");
            }
            return Redirect("~/Chef/ChefS/ManageSupp");
        }
        //Manage Material
        public ActionResult ManageMaterial()
        {
            return View(db.INGREDIENT.ToList());
        }
        public ActionResult Addmaterial()
        {
            return View(new MaterialValidate());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Addmaterial(MaterialValidate mr)
        {
            var checkma = db.INGREDIENT.Any(x => x.C_Material_id == mr.MaterialID);
            if (checkma == false)
            {
                INGREDIENT mrAdd = new INGREDIENT();
                mrAdd.C_Material_id = mr.MaterialID;
                mrAdd.C_Material_name = mr.MaterialName;
                mrAdd.C_Quantity_I = mr.MaterialQT;
                mrAdd.C_Unit = mr.MaterialUnit;
                db.INGREDIENT.Add(mrAdd);
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageMaterial");
            }
            else
            {
                ViewBag.err = "Material already exist";
                return View(mr);
            }
        }
        public ActionResult Updatematerial(String id)
        {
            var checkmt = db.INGREDIENT.Where(n => n.C_Material_id == id).FirstOrDefault();
            MaterialValidate mt = new MaterialValidate();
            mt.MaterialID = checkmt.C_Material_id;
            mt.MaterialName = checkmt.C_Material_name;
            mt.MaterialQT = checkmt.C_Quantity_I;
            mt.MaterialUnit = checkmt.C_Unit;
            return View(mt);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Updatematerial(MaterialValidate mr)
        {
            var checkmr = db.INGREDIENT.Where(n => n.C_Material_id == mr.MaterialID).FirstOrDefault();
            if (checkmr != null)
            {
                checkmr.C_Material_id = mr.MaterialID;
                checkmr.C_Material_name = mr.MaterialName;
                checkmr.C_Quantity_I = mr.MaterialQT;
                checkmr.C_Unit = mr.MaterialUnit;
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageMaterial");
            }
            else
            {
                ViewBag.err = "Material ID does not exist";
                return View(mr);
            }
        }
        public ActionResult Deletematerial(String id)
        {
            var mr = db.INGREDIENT.Where(n => n.C_Material_id == id).FirstOrDefault();
            if (mr != null)
            {
                db.INGREDIENT.Remove(mr);
                db.SaveChanges();
                return Redirect("~/Chef/ChefS/ManageMaterial");
            }
            return Redirect("~/Chef/ChefS/ManageMaterial");
        }
        //View Registration
        public ActionResult ViewRegis()
        {
            return View(db.ORDERS.ToList());
        }
    }
}

FMS/FMS/FMS/Areas/Admin/Views/Chef/Addfood.cshtml
@using FMS.Models
@model FoodValidate
@{
    Layout = "~/Views/Shared/_logoutlayout.cshtml";
    ViewBag.Title = "Create food";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create food</title>
    <link rel="stylesheet" href="~/Content/admincss/menuadim/homepageadmin.css">>
    <link rel="stylesheet" href="~/Content/admincss/menuadim/manageall.css">
    <link rel="stylesheet" href="~/Content/admin/4.staff/orderfood.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

</head>

<body>
    <!-- html cho phần menu -->
    <div class="navigation open">
        <div class="menuToggle">Admin</div>
        <div class="main-menu">
            <div class="dropdown">
                <input type="text" class="text02" readonly placeholder="Dropdown Menu">
                <div class="options">
                    <div class="change-option-admin" onmouseover="show('Admin')">Admin</div>
                    <div class="change-option-manage" onmouseover="show('Management')">Management</div>
                    <div class="change-option-cheif" onmouseover="show('Cheif')">Cheif</div>
                    <div class="change-option-staff" onmouseover="show('Staff')">Staff</div>
                </div>
            </div>
            <div class="menu-option">
                <ul class="admin">
                    <li class="list " style="--clr:#f44336;">
                        <a href="@Url.Action("ManageAcc","Admin")">
                            <span class="icon"><ion-icon name="desktop-outline"></ion-icon></span>
                            <span class="text">Manage Account</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("ManageEmploy","Admin")">
                            <span class="icon"><ion-icon name="people-outline"></ion-icon></span>
                            <span class="text">Manage Employee</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#4f088a;">
                        <a href="@Url.Action("ManageDepart","Admin")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Manage Department</span>
                        </a>
                    </li>
                    <li class="list " style="--clr:#0fc70f;">
                        <a href="@Url.Action("FaceID","Admin")">
                            <span class="icon"><ion-icon name="grid-outline"></ion-icon></span>
                            <span class="text">Manage Face Pattern</span>
                        </a>
                    </li>
                </ul>
                <ul class="manage">
                    <li class="list" style="--clr:#f44336;">
                        <a href="@Url.Action("ManagePro","Manager")">
                            <span class="icon"><ion-icon name="newspaper-outline"></ion-icon></span>
                            <span class="text">Manage Profile</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("ManageWorkshift","Manager")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Manage WorkShift</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#4f088a;">
                        <a href="@Url.Action("TimeKeeping","Manager")">
                            <span class="icon"><ion-icon name="today-outline"></ion-icon></span>
                            <span class="text">TimeKeeping</span>
                        </a>
                    </li>
                    <li class="list " style="--clr:#2196f3;">
                        <a href="@Url.Action("ReportStatis","Manager")">
                            <span class="icon"><ion-icon name="document-text-outline"></ion-icon></span>
                            <span class="text">Report Statistics</span>
                        </a>
                    </li>
                </ul>
                <ul class="cheif showcheif">
                    <li class="list active" style="--clr:#f44336;">
                        <a href="@Url.Action("ManageMenu","Chef")">
                            <span class="icon"><ion-icon name="receipt-outline"></ion-icon></span>
                            <span class="text">Manage Menu</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("ManageSupp","Chef")">
                            <span class="icon"><ion-icon name="receipt-outline"></ion-icon></span>
                            <span class="text">Manage Supplier</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#4f088a;">
                        <a href="@Url.Action("ManageMaterial","Chef")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Manage Material</span>
                        </a>
                    </li>
                    <li class="list " style="--clr:#0fc70f;">
                        <a href="@Url.Action("ViewRegis","Chef")">
                            <span class="icon"><ion-icon name="clipboard-outline"></ion-icon></span>
                            <span class="text">View Registration</span>
                        </a>
                    </li>
                </ul>
                <ul class="staff">
                    <li class="list" style="--clr:#f44336;">
                        <a href="@Url.Action("Order", "Staff")">
                            <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                            <span class="text">Order</span>
                        </a>
                    </li>
                    <li class="list" style="--clr:#ffa117;">
                        <a href="@Url.Action("PersonalPro", "Staff")">
                            <span class="icon"><ion-icon name="person-outline"></ion-icon></span>
                            <span class="text">Personal profile</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- end menu -->
    <!-- html cho phần nội dung -->
    <div class="home-main open3">
        <hr>
        @using (Html.BeginForm("Addfood", "Chef", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="table-food">
                <div class="khungtable">
                    <div class="khungtren">
                        <div class="order-right">
                            <div class="rowtext">
                                <p style="margin-right:8%">Food ID: </p>
                                @Html.TextBoxFor(m => m.FoodID, "", new { @class = " ", placeholder = "Food ID" })
                                @*<input type="text" placeholder="food ID">*@
                            </div>
                            <div class="rowtext">
                                <p>Food Name: </p>
                                @Html.TextBoxFor(m => m.FoodName, "", new { @class = " ", placeholder = "Food Name" })
                                @*<input type="text" placeholder="food Name">*@
                            </div>
                            <div class="rowtext">
                                <p>Description: </p>
                                @Html.TextBoxFor(m => m.FoodDescrip, "", new { @class = " ", placeholder = "Food Description" })
                                @*<input type="text" placeholder="Description">*@
                            </div>
                            <div class="rowtext">
                                <p>Food Image: </p>
                                <input type="file" placeholder="Chose file">
                            </div>
                        </div>
                        <div class="order-image">
                            <img src="/kitchen/images/hướng dương.jpg" alt="" width="100%">
                        </div>
                    </div>
                    <div class="btn-order">
                        <button type="submit" class="btn btn-success">Create</button>
                        <a class="btn btn-danger" href="@Url.Action("ManageMenu","Chef")">Cancel</a>
                    </div>
                </div>

            </div>
        }
    </div>
    <!-- end nội dung -->

    <script>
        // script cho phần profile
        let menuToggleprofile = document.querySelector('.menuToggle-profile');
        let navigationprofile = document.querySelector('.navigation-profile')
        menuToggleprofile.onclick = function () {
            navigationprofile.classList.toggle('active')
        }

        // script cho phần option role
        function show(a) {
            document.querySelector('.navigation.open .text02').value = a;
        }

        let dropdown = document.querySelector('.dropdown');
        dropdown.onclick = function () {
            dropdown.classList.toggle('dropdownactive');
        }

        //script cho phần đổi menu
        const changeadmin = document.querySelector('.change-option-admin');
        const changemanage = document.querySelector('.change-option-manage');
        const changecheif = document.querySelector('.change-option-cheif');
        const changestaff = document.querySelector('.change-option-staff');
        const admin = document.querySelector('.admin');
        const manage = document.querySelector('.manage');
        const cheif = document.querySelector('.cheif');
        const staff = document.querySelector('.staff');

        changeadmin.onclick = function () {
            admin.classList.add('showadmin');
            manage.classList.remove('showmanage');
            cheif.classList.remove('showcheif');
            staff.classList.remove('showstaff');
        }
        changemanage.onclick = function () {
            admin.classList.remove('showadmin');
            manage.classList.add('showmanage');
            cheif.classList.remove('showcheif');
            staff.classList.remove('showstaff');
        }
        changecheif.onclick = function () {
            admin.classList.remove('showadmin');
            manage.classList.remove('showmanage');
            cheif.classList.add('showcheif');
            staff.classList.remove('showstaff');
        }
        changestaff.onclick = function () {
            admin.classList.remove('showadmin');
            manage.classList.remove('showmanage');
            cheif.classList.remove('showcheif');
            staff.classList.add('showstaff');
        }
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>

FMS/FMS/FMS/Areas/Admin/Views/Chef/DeleteSupp.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeleteSupp</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

FMS/FMS/FMS/Areas/Admin/Views/Chef/Deletefood.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Deletefood</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

FMS/FMS/FMS/Areas/Admin/Views/Chef/Deletematerial.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Deletematerial</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>